### ISSUE TITLE
For generated scene graphs

### ISSUE THREAD

**Issue by HA-sala** [aluo-x/3D_SLN#1]
Hello, thank you very much. Your work has been of great help to me. I used my datasets  to train the network model and got KL_Loss = 0.05. However, when I use the same scene graph to guide the synthesis of scene layouts, I can only get the same generated scene graphs (little difference). why? Did I miss an important step?

for k in range(Nsample):
     z = torch.from_numpy(np.random.multivariate_normal(mean_est, cov_est, objs.size(0))).float().cuda()
     boxes_pred, angles_pred = model.decoder(z, objs, triples, attributes)

Nsample = 4 , Four boxes_preds are the same(little difference).

**Comment by aluo-x** [comment]
Can you clarify the dataset that you use?

**Comment by HA-sala** [comment]
Each sample is a bunch of boxes placed under some constraint, and there are 30k samples.

**Comment by aluo-x** [comment]
To clarify, you are not using the SUNCG dataset, but this is a dataset that you created yourself?

**Comment by HA-sala** [comment]
Yes, Create dataset by imitating the matedata of SUNCG Dataset. Each data contains the central coordinates of the box, the length, width and height of the box, and other information

**Comment by aluo-x** [comment]
Here are a few suggestions that you may try:
1. Change the weight between reconstruction and the VAE regularization (`KL_loss_weight`)
2. During test time use the prior (Normal distribution with zero mean, unit variance), instead of the posterior (mean_est, cov_est)
3. Double check the data, and the scene graphs generated are valid (print out the triples). It is possible that your data has a different "coordinate frame" than SUNCG

I also provide tools to help with visualizing the model output in `test_heatmap.py`, this is a function which can take in scene graphs and use the trained model to produce a heatmap of distributions,

**Comment by HA-sala** [comment]
Thanks. I'll try your Suggestions
